# Streamlit Cloud Secrets Configuration

# Langfuse API Keys
LANGFUSE_SECRET_KEY = "your_langfuse_secret_key_here"
LANGFUSE_PUBLIC_KEY = "your_langfuse_public_key_here"
LANGFUSE_HOST = "http://localhost:3000"

# OpenAI API Configuration
OPENAI_API_KEY = "your_openai_api_key_here"
OPENAI_API_BASE = "https://api.openai.com/v1"
OPENAI_MODEL = "gpt-4o-mini"

# Embedding API Configuration
EMBEDDING_API_KEY = "your_openai_api_key_here"
EMBEDDING_API_BASE = "https://api.openai.com/v1"
EMBEDDING_MODEL = "text-embedding-3-small"

# Vector Database Configuration
VECTOR_DB_HOST = "localhost"
VECTOR_DB_PORT = 19530
VECTOR_DB_DATABASE = "examples"
# Authentication
VECTOR_DB_USER = ""
VECTOR_DB_PASSWORD = ""
VECTOR_DB_TOKEN = ""
# Vector dimension for embeddings
VECTOR_EMBEDDING_DIMENSION = 1024